- name: users | robk | remove preinstalled clutter from home directory
  file:
    path: /home/robk/{{ item }}
    state: absent
  with_items:
    - examples.desktop
#    - Desktop
#    - Documents
#    - Downloads
#    - Music
#    - Pictures
#    - Public
#    - Templates
#    - Videos

- name: users | robk | create personal config directories
  tags: dotfiles,dotfiles-robk
  file:
    path: /home/robk/{{ item.dir }}
    state: directory
    owner: robk
    group: robk
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/terminator }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
#    - { dir: bin }
#    - { dir: desktop }
#    - { dir: documents }
#    - { dir: downloads }
#    - { dir: projects }
#    - { dir: templates }

#- name: users | robk | copy user-dirs.dirs
#  tags: dotfiles,dotfiles-robk
#  copy:
#    src: users/robk/user-dirs.dirs
#    dest: /home/robk/.config/user-dirs.dirs
#    owner: robk
#    group: robk
#    mode: 0600
#  notify: update_xdg

- name: users | robk | copy personal config files
  tags: dotfiles,dotfiles-robk
  copy:
    src: users/robk/{{ item.src }}
    dest: /home/robk/{{ item.dest }}
    owner: robk
    group: robk
    mode: 0600
  with_items:
#    - { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }
#    - { src: 'gvimrc', dest: '.gvimrc' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
    - { src: 'terminator_config', dest: '.config/terminator/config' }

- name: users | robk | copy profile image
  tags: dotfiles,dotfiles-robk
  copy:
    src: users/robk/profile_image.png
    dest: /var/lib/AccountsService/icons/robk.png
    owner: root
    group: root
    mode: 0644
