- name: system setup | package cleanup | remove unneeded packages
  tags: packages,system,settings
  package:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]