- name: Apply general desktop role
  import_role:
    name: desktop_general
  when: "'desktop_general' in group_names"

- name: Apply development desktop role
  import_role:
    name: desktop_development
  when: "'desktop_development' in group_names"  