# This is a task file, not a playbook

- name: Apply IAC role
  ansible.builtin.import_role:
    name: server_iac
  when: "'server_iac' in group_names"

- name: Apply Docker role
  ansible.builtin.import_role:
    name: server_docker
  when: "'server_docker' in group_names"

- name: Apply Swarm Manager role
  ansible.builtin.import_role:
    name: server_swarm_manager
  when: "'server_swarm_manager' in group_names"

- name: Apply Swarm Host role
  ansible.builtin.import_role:
    name: server_swarm_host
  when: "'server_swarm_host' in group_names"

- name: Apply Utility role
  ansible.builtin.import_role:
    name: server_utility
  when: "'server_utility' in group_names"
