- name: software | kdenlive | copy launcher
  tags: apps,appimage,software,kdenlive
  copy:
    src: users/robk/kdenlive.desktop
    dest: /home/robk/.local/share/applications/kdenlive.desktop
    owner: robk
    group: robk
    mode: 0700

- name: software | kdenlive | install package
  get_url:
    url: https://download.kde.org/stable/kdenlive/20.08/linux/kdenlive-20.08.2-x86_64.appimage
    dest: /home/robk/bin/kdenlive.app
    mode: '0700'
    owner: robk
    group: robk
