- name: software | mattermost | install package
  tags: packages,flatpak,mattermost,workstation-packages
  become_user: robk
  flatpak:
    name: com.mattermost.Desktop
    method: user
    state: present
  when: mattermost is defined and mattermost == true

- name: software | mattermost | enable autostart
  tags: packages,flatpak,mattermost,workstation-packages
  file:
    src: /home/robk/.local/share/flatpak/exports/share/applications/com.mattermost.Desktop.desktop
    dest: /home/robk/.config/autostart/com.mattermost.Desktop.desktop
    owner: robk
    group: robk
    state: link
  when: mattermost is defined and mattermost == true
