- name: software | ulauncher | install ppa
  tags: ulauncher
  apt_repository:
    repo: 'ppa:agornostal/ulauncher'
    state: present
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - ulauncher is defined
    - ulauncher == true

- name: software | ulauncher | install package
  tags: ulauncher
  apt:
    name: ulauncher
    state: latest
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - ulauncher is defined
    - ulauncher == true

- name: software | ulauncher | enable autostart
  tags: ulauncher
  copy:
    src: users/robk/ulauncher.desktop
    dest: /home/robk/.config/autostart/ulauncher.desktop
    owner: robk
    group: robk
    mode: 0600
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - ulauncher is defined
    - ulauncher == true
